version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lauf_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-lauf_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 450M # Proteje sua VPS limitando quantia de RAM do banco de dados

volumes:
  postgres_data_prod:
